apiVersion: v1
kind: Secret
metadata:
  name: {{ template "node.fullname" . }}-great-secret
  labels:
    object: {{ template "node.fullname" . }}-great-secret
type: Opaque
data:
  config.yaml: |
    {{ default "" .Values.additional_yaml | toString | b64enc }}
